---
driver:
  name: ec2
  availability_zone: us-west-2a
  region: us-west-2

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[kitchen-drivers::default]
    attributes:
